### PR TITLE
Use instancetype instead of id

### PR DESCRIPTION
**Pull request by jPaolantonio**
Convert ids to instancetype

### CODE REVIEW

**Comment by jPaolantonio** [comment]
@f2prateek I think this should solve https://github.com/segment-integrations/analytics-ios-integration-mixpanel/issues/2 . Does this make sense for you?

**Comment by f2prateek** [comment]
LGTM!

**Comment by jPaolantonio** [comment]
@f2prateek Can we add a new tag, maybe `1.0.3`?

**Comment by f2prateek** [comment]
@jPaolantonio just deployed 1.0.3

**Pull request merged**
